# Generated by Django 6.0.2 on 2026-02-25 20:33

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0001_initial'),
        ('locations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TouristSpotImage',
            fields=[
                ('deleted', models.DateTimeField(db_index=True, editable=False, null=True)),
                ('deleted_by_cascade', models.BooleanField(default=False, editable=False)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('image', models.ImageField(upload_to='locations/images/')),
                ('caption', models.CharField(blank=True, max_length=200)),
                ('is_cover', models.BooleanField(default=False)),
                ('order', models.PositiveBigIntegerField(default=0)),
            ],
            options={
                'db_table': 'tourist_spot_images',
                'ordering': ['order', '-created_at'],
            },
        ),
        migrations.AddField(
            model_name='touristspot',
            name='categories',
            field=models.ManyToManyField(blank=True, related_name='spots', to='categories.category'),
        ),
        migrations.AddIndex(
            model_name='touristspot',
            index=models.Index(fields=['city'], name='tourist_spo_city_a22b0c_idx'),
        ),
        migrations.AddIndex(
            model_name='touristspot',
            index=models.Index(fields=['department'], name='tourist_spo_departm_68f960_idx'),
        ),
        migrations.AddIndex(
            model_name='touristspot',
            index=models.Index(fields=['is_featured'], name='tourist_spo_is_feat_bb95c5_idx'),
        ),
        migrations.AddField(
            model_name='touristspotimage',
            name='spot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='locations.touristspot'),
        ),
        migrations.AddIndex(
            model_name='touristspotimage',
            index=models.Index(fields=['spot', 'is_cover'], name='tourist_spo_spot_id_7f8e3b_idx'),
        ),
    ]
