# Generated by Django 6.0.2 on 2026-02-26 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0002_touristspotimage_touristspot_categories_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='touristspot',
            name='average_rating',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=3),
        ),
        migrations.AddField(
            model_name='touristspot',
            name='reviews_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
